version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5
        environment:
          RAILS_ENV: test
          ROOMRES_DB_PASSWORD: ""
          ROOMRES_DB_PORT: "3306"
          ROOMRES_DB_USERNAME: root
          ROOMRES_DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.7.22
        environment:
          MYSQL_DATABASE: roomreservation_test
    working_directory: ~/roomres
    steps:
      - run:
          name: Update Debian Packages
          command: |
            echo "deb http://http.debian.net/debian jessie-backports main" | sudo tee -a /etc/apt/sources.list
            sudo apt-get update -qq
            sudo apt-get upgrade -qq
            sudo apt-get install -y -f software-properties-common build-essential default-libmysqlclient-dev mysql-client nodejs make apt-utils memcached phantomjs libfontconfig
      - checkout
      - run:
          name: Setup config.yml
          command: cp config/config.example.yml config/config.yml
      - restore_cache:
          key: gemfile-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby Dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: gemfile-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
            - tmp/zips
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Create DB
          command: bundle exec rake db:create db:schema:load --trace
      - run:
          name: Run Tests
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: /tmp/circle-junit
