default:
  plugins:
    - textcolor
    - link
    - fullscreen
    - preview
    - code
    - contextmenu
  toolbar:
    - undo
    - redo
    - formatselect
    - fontselect
    - fontsizeselect
    - bold
    - italic
    - alignleft
    - aligncenter
    - alignright
    - alignjustify
    - bullist
    - numlist
    - outdent
    - indent
    - link
    - forecolor
  contextmenu: "preview code fullscreen"